M48
; DRILL file {KiCad 9.0.9-9.0.9~ubuntu24.04.1} date 2026-10-04T14:20:18+0000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-10-04T14:20:18+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.9-9.0.9~ubuntu24.04.1
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.300
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.750
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.200
%
G90
G05
T1
X7.895Y-9.0
T2
X7.0Y-15.0
X9.0Y-15.0
X11.0Y-15.0
X13.0Y-15.0
T3
X2.5Y-2.5
X17.5Y-17.5
M30
