cmake_minimum_required(VERSION 3.13)
include($ENV{PICO_SDK_PATH}/external/pico_sdk_import.cmake)
project(qulay_r2 C CXX ASM)
set(CMAKE_C_STANDARD 11)
set(CMAKE_CXX_STANDARD 17)
pico_sdk_init()
add_executable(qulay_r2 main.c)
target_include_directories(qulay_r2 PRIVATE ../include)
target_link_libraries(qulay_r2 pico_stdlib hardware_spi hardware_irq hardware_sync)
target_compile_options(qulay_r2 PRIVATE -Wall -Wextra)
pico_enable_stdio_usb(qulay_r2 1)
pico_enable_stdio_uart(qulay_r2 0)
pico_add_extra_outputs(qulay_r2)
option(QULAY_BENCH_THREE "Compile for only three AS5048A devices in bank0" OFF)
if(QULAY_BENCH_THREE)
 target_compile_definitions(qulay_r2 PRIVATE QULAY_BENCH_THREE=1)
endif()
