<project xmlns="http://maven.apache.org/POM/4.0.0"><modelVersion>4.0.0</modelVersion><parent><groupId>org.qulay</groupId><artifactId>qulay</artifactId><version>0.1.0</version><relativePath>../../pom.xml</relativePath></parent><artifactId>desktop</artifactId><properties><app.main>org.qulay.desktop.DesktopApp</app.main></properties><dependencies><dependency><groupId>org.qulay</groupId><artifactId>core</artifactId></dependency></dependencies><build><plugins><plugin><groupId>org.apache.maven.plugins</groupId><artifactId>maven-shade-plugin</artifactId></plugin></plugins></build></project>
