M48
; DRILL file {KiCad 9.0.9-9.0.9~ubuntu24.04.1} date 2026-10-04T14:20:10+0000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-10-04T14:20:10+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.9-9.0.9~ubuntu24.04.1
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.750
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X5.0Y-9.5
X7.0Y-9.5
X9.0Y-9.5
T2
X2.0Y-2.0
X16.0Y-10.0
M30
